// This file is auto-generated by Convex.
// Run `npx convex dev` to generate the actual types.

import { v } from "convex/values";

export function query(args: { args: any; handler: any }): any;
export function mutation(args: { args: any; handler: any }): any;
export function internalQuery(args: { args: any; handler: any }): any;
export function internalMutation(args: { args: any; handler: any }): any;
export { v };
